### ISSUE TITLE
Optionally remove top level headings

### ISSUE THREAD

**Issue by ispringle** [igorskyflyer/npm-astro-post-excerpt#12]
I'm wondering if there might be a good way to optionally remove the top level heading from the content to be excerpted. Two fairly common patterns for markdown files is to insert either a 
```md
# Heading at the Top of the File
```

or a 
```md
# Heading at the Top of the File

## Followed By a Second Heading
```

For an except it doesn't make much sense to grab headings, so to be able to at least optionally ignore all headings would be great.

**Comment by igorskyflyer** [comment]
Indeed, will be added to the next release. Thanks for your suggestion.
Stay tuned. 😌
